# Generated by Django 4.0.6 on 2022-09-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=400)),
                ('account_no', models.CharField(max_length=400)),
                ('account_status', models.CharField(max_length=400)),
            ],
        ),
    ]
